using System.Collections.Generic;
using System.IO;
using NUnit.Framework;
using UnityEditor.Animations;
using UnityEngine;
using Yozolab.DaerD.Authoring;

namespace Yozolab.DaerD.Tests
{
    /// <summary>
    /// The scripted route into the exporter — the one a test, an editor script or a batch job
    /// uses. What is checked here is that it stands on its own: no window, no project folder,
    /// and no side effect the caller didn't ask for.
    ///
    /// The project route (<see cref="RecipeExport.ToProject"/>) is deliberately not exercised:
    /// it queues an asset that only exists after the next compile, so its shape belongs to the
    /// window's own path. What both routes share — deciding the class name, choosing the layer
    /// subset, writing the two halves — is what these tests cover.
    /// </summary>
    public class RecipeExportApiTests
    {
        readonly List<Object> _cleanup = new List<Object>();
        string _dir;

        [SetUp]
        public void SetUp()
        {
            // Outside Assets on purpose: an analysis that reads a controller as C# should be
            // able to land its output somewhere the asset pipeline never sees.
            _dir = Path.Combine(Path.GetTempPath(), "daerd-export-" + Path.GetRandomFileName());
        }

        [TearDown]
        public void TearDown()
        {
            foreach (var o in _cleanup)
                if (o != null) Object.DestroyImmediate(o);
            _cleanup.Clear();
            if (_dir != null && Directory.Exists(_dir)) Directory.Delete(_dir, true);
        }

        AnimatorController Sample()
        {
            var controller = new AnimatorController { name = "Sample FX" };
            _cleanup.Add(controller);
            controller.AddParameter("Alpha", AnimatorControllerParameterType.Bool);
            controller.AddParameter("Beta", AnimatorControllerParameterType.Bool);

            controller.AddLayer("First");
            var first = controller.layers[0].stateMachine;
            var a = first.AddState("A", new Vector3(100f, 50f, 0f));
            var b = first.AddState("B", new Vector3(100f, 150f, 0f));
            var transition = a.AddTransition(b);
            transition.AddCondition(AnimatorConditionMode.If, 0f, "Alpha");

            controller.AddLayer("Second");
            var second = controller.layers[1].stateMachine;
            var c = second.AddState("C", new Vector3(100f, 50f, 0f));
            second.AddAnyStateTransition(c)
                .AddCondition(AnimatorConditionMode.If, 0f, "Beta");
            return controller;
        }

        [Test]
        public void SourceCarriesBothHalvesAndDefaultsItsNameFromTheController()
        {
            var source = RecipeExport.ToSource(Sample());

            Assert.AreEqual("SampleFXRecipe", source.className);
            StringAssert.StartsWith("// <auto-generated>", source.code);
            StringAssert.Contains("public partial class SampleFXRecipe : ControllerRecipe",
                source.code);
            StringAssert.StartsWith(RecipeExporter.HandHalfMarker, source.handHalf);
            Assert.IsEmpty(source.warnings, string.Join("\n", source.warnings.ToArray()));
        }

        [Test]
        public void VerifyIsEmptyWhenTheRecipeRebuildsTheController()
        {
            var controller = Sample();
            var source = RecipeExport.ToSource(controller);

            var differences = RecipeExport.Verify(controller, source);

            Assert.IsEmpty(differences, string.Join("\n", differences.ToArray()));
            // Cached: asking twice must not re-run the comparison into a different answer.
            Assert.AreSame(differences, RecipeExport.Verify(controller, source));
        }

        [Test]
        public void ALayerSubsetExportsOnlyThoseLayersAndTheirParameters()
        {
            var source = RecipeExport.ToSource(Sample(),
                new RecipeExport.Options { layerNames = new[] { "Second" } });

            StringAssert.Contains("c.Layer(\"Second\")", source.code);
            StringAssert.DoesNotContain("c.Layer(\"First\")", source.code);
            StringAssert.Contains("c.BoolParameter(\"Beta\")", source.code);
            StringAssert.DoesNotContain("c.BoolParameter(\"Alpha\")", source.code);
        }

        [Test]
        public void EveryLayerNamedIsTheSameAsNamingNone()
        {
            var controller = Sample();

            string all = RecipeExport.ToSource(controller,
                new RecipeExport.Options { layerNames = new[] { "First", "Second" } }).code;

            Assert.AreEqual(RecipeExport.ToSource(controller).code, all,
                "a full subset is an exclusive recipe, not a partial one");
        }

        [Test]
        public void ToDirectoryWritesTheTwoHalvesAndNothingElse()
        {
            var written = RecipeExport.ToDirectory(Sample(), _dir);

            Assert.AreEqual(Path.Combine(_dir, "SampleFXRecipe.Generated.cs").Replace('\\', '/'),
                written.generatedPath.Replace('\\', '/'));
            FileAssert.Exists(written.generatedPath);
            FileAssert.Exists(written.handHalfPath);
            Assert.IsTrue(written.wroteHandHalf);
            Assert.IsFalse(written.codeUnchanged);
            Assert.AreEqual(2, Directory.GetFiles(_dir).Length,
                "no assembly definition, no .asset, no .meta — this folder isn't in a project");
        }

        [Test]
        public void ReExportingLeavesTheHandHalfAloneAndSkipsAnIdenticalWrite()
        {
            var controller = Sample();
            var first = RecipeExport.ToDirectory(controller, _dir);
            File.WriteAllText(first.handHalfPath, "// mine\n");

            var again = RecipeExport.ToDirectory(controller, _dir);

            Assert.IsTrue(again.codeUnchanged, "the same controller exports byte-identical code");
            Assert.IsFalse(again.wroteHandHalf);
            Assert.AreEqual("// mine\n", File.ReadAllText(again.handHalfPath).Replace("\r\n", "\n"));
        }

        [Test]
        public void ANamespaceReachesBothHalves()
        {
            var written = RecipeExport.ToDirectory(Sample(), _dir,
                new RecipeExport.Options { namespaceName = "My.Space" });

            StringAssert.Contains("namespace My.Space", File.ReadAllText(written.generatedPath));
            StringAssert.Contains("namespace My.Space", File.ReadAllText(written.handHalfPath));
        }

        [Test]
        public void AProjectExportRefusesAFolderOutsideTheProject()
        {
            Assert.Throws<System.ArgumentException>(
                () => RecipeExport.ToProject(Sample(), _dir));
        }

        [Test]
        public void AProjectFolderGainsAnEditorLeafButKeepsAnExistingOne()
        {
            Assert.AreEqual("Assets/Recipes/Editor",
                RecipeExport.ResolveProjectFolder("Assets/Recipes"));
            Assert.AreEqual("Assets/Editor/Recipes",
                RecipeExport.ResolveProjectFolder("Assets/Editor/Recipes"));
            Assert.IsNull(RecipeExport.ResolveProjectFolder("/somewhere/else"));
        }

        [Test]
        public void OnlyAPreSplitRecipeCountsAsASingleFileOne()
        {
            var written = RecipeExport.ToDirectory(Sample(), _dir);
            Assert.IsFalse(RecipeExport.IsSingleFileRecipe(written.handHalfPath),
                "a hand half is not the old single-file shape");
            Assert.IsFalse(RecipeExport.IsSingleFileRecipe(Path.Combine(_dir, "Nothing.cs")));

            string old = Path.Combine(_dir, "Old.cs");
            File.WriteAllText(old, "public class Old : ControllerRecipe { }\n");
            Assert.IsTrue(RecipeExport.IsSingleFileRecipe(old));
        }

        // ---- batch-mode arguments ----------------------------------------------

        [Test]
        public void TheCommandLineParsesControllersFlagsAndLayers()
        {
            var args = RecipeExportCli.Parse(new[]
            {
                "/opt/Unity", "-batchmode", "-projectPath", "P",
                "-daerdController", "Assets/A.controller",
                "-daerdOut", "/tmp/out", "-daerdNamespace", "My.Space",
                "-daerdLayers", "One;Two", "-daerdNoAsset", "-daerdVerify",
            });

            Assert.AreEqual(new[] { "Assets/A.controller" }, args.controllers.ToArray());
            Assert.AreEqual("/tmp/out", args.outFolder);
            Assert.AreEqual("My.Space", args.namespaceName);
            Assert.AreEqual(new[] { "One", "Two" }, args.layers.ToArray());
            Assert.IsFalse(args.createAsset);
            Assert.IsTrue(args.createAsmdef, "only what was asked for is switched off");
            Assert.IsTrue(args.verify);
            Assert.IsFalse(args.migrate, "rewriting a pre-split recipe is opt-in");
        }

        [Test]
        public void TheCommandLineRejectsMisuse()
        {
            Assert.Throws<System.ArgumentException>(
                () => RecipeExportCli.Parse(new[] { "-batchmode" }),
                "an export needs a controller");
            Assert.Throws<System.ArgumentException>(
                () => RecipeExportCli.Parse(new[] { "-daerdController" }),
                "a flag that takes a value needs one");
            // One name, two controllers: the second export would land on the first's files.
            Assert.Throws<System.ArgumentException>(() => RecipeExportCli.Parse(new[]
            {
                "-daerdController", "Assets/A.controller",
                "-daerdController", "Assets/B.controller",
                "-daerdClass", "Both",
            }));
            Assert.Throws<System.ArgumentException>(() => RecipeExportCli.Parse(new[]
            {
                "-daerdController", "Assets/A.controller",
                "-daerdController", "Assets/B.controller",
                "-daerdLayers", "One",
            }));
        }
    }
}
