using System;
using System.Collections.Generic;
using UnityEditor;
using UnityEditor.Animations;
using UnityEngine;

namespace Yozolab.DaerD
{
    /// <summary>
    /// The dedicated view for a generated async-sync layer, shown in the centre pane instead
    /// of the graph: the layer's states are machinery nobody hand-edits, so what the layer IS
    /// — the multiplexed targets, their order, rates and requestable marks, the cost and the
    /// cycle — is the thing worth looking at. Hosts the shared <see cref="AsyncSyncForm"/>
    /// prefilled from the layer's saved setup, applies straight back onto this layer, and
    /// lists the states that raise sync requests against it. The raw graph stays one click
    /// away (<see cref="ShowGraphRequested"/>).
    /// </summary>
    class AsyncSyncPanel : PanelBase
    {
        readonly AsyncSyncForm _form = new AsyncSyncForm();
        AnimatorController _boundController;
        AnimatorStateMachine _boundLayer;

        /// <summary>Raised when the user asks for the underlying state machine graph.</summary>
        public Action ShowGraphRequested;

        public AsyncSyncPanel(DaerDContext context) : base(context, "Async Sync")
        {
            // The AAP set the warnings read is cached across repaints; these are the changes
            // that can add or remove an animated write, and they are the same two
            // ParametersPanel drops its own copy of the set on.
            context.GraphStructureChanged += _form.InvalidateAnimatedParameters;
            context.ParametersChanged += _form.InvalidateAnimatedParameters;
        }

        /// <summary>The saved setup owning this machine, or null — this is what decides
        /// whether a layer gets this panel instead of the graph.</summary>
        public static GraphFrameData.AsyncSyncConfig ConfigOf(AnimatorController controller,
            AnimatorStateMachine machine)
        {
            if (controller == null || machine == null) return null;
            foreach (var config in GraphFrameData.GetAsyncSyncs(controller))
                if (config.layer == machine)
                    return config;
            return null;
        }

        protected override void DrawContent()
        {
            var controller = Context.Controller;
            var machine = Context.CurrentLayer?.stateMachine;
            var config = ConfigOf(controller, machine);
            if (config == null)
            {
                // Only reachable in the frame between a structural change and the host
                // switching back to the graph.
                EditorGUILayout.LabelField(L.Tr("This layer has no async sync setup."),
                    EditorStyles.centeredGreyMiniLabel);
                return;
            }

            // Rebind when the layer under the panel changes; editing keeps the form's state
            // otherwise, exactly like the wizard.
            if (_boundController != controller || _boundLayer != machine)
            {
                _boundController = controller;
                _boundLayer = machine;
                _form.SetController(controller);
                _form.LoadConfig(config);
            }

            EditorGUILayout.BeginHorizontal();
            EditorGUILayout.LabelField(
                L.Tr("Async sync layer '{0}'", Context.CurrentLayer.name),
                EditorStyles.boldLabel);
            GUILayout.FlexibleSpace();
            if (GUILayout.Button(L.Tr("Show Graph"), EditorStyles.miniButton, GUILayout.Width(90)))
                ShowGraphRequested?.Invoke();
            EditorGUILayout.EndHorizontal();
            EditorGUILayout.LabelField(
                L.Tr("This layer is generated machinery — edit the setup here and apply; the states are rebuilt in place."),
                EditorStyles.miniLabel);

            var codeOwned = GraphFrameData.GetCodeOwned(controller);
            if (machine != null && codeOwned.TryGetValue(machine, out var recipe))
                EditorGUILayout.HelpBox(
                    L.Tr("Generated by recipe '{0}' — Generate on that asset rebuilds this layer", recipe.name),
                    MessageType.Info);

            EditorGUILayout.Space(4);
            _form.DrawGeneratedSection();
            EditorGUILayout.Space(4);
            _form.DrawPickList();

            var request = _form.BuildRequest(Context.LayerIndex);
            EditorGUILayout.Space(4);
            _form.DrawOrderSection(request);
            _form.DrawPreview(request);
            _form.DrawBlockingProblem(request);
            // Worked out once and read twice: the warnings quote it and the button below acts
            // on it, and it is the most expensive answer this draw asks for.
            var byType = AsyncSyncSplit.ByType(request);
            foreach (var warning in AsyncSyncBuilder.Warnings(request, _form.AnimatedParameters(), byType))
                EditorGUILayout.HelpBox(warning, MessageType.Warning);
            // The split rebuilt this layer as one type's ring and added the others; the form
            // is holding the setup that no longer exists, so it is rebound from what was saved.
            if (_form.DrawSplitProposal(request, byType))
            {
                _boundLayer = null;
                Context.NotifyParametersChanged();
                Context.NotifyGraphStructureChanged();
                GUIUtility.ExitGUI();
            }
            _form.DrawStoreFix(request);

            EditorGUILayout.Space(4);
            EditorGUILayout.BeginHorizontal();
            GUILayout.FlexibleSpace();
            if (GUILayout.Button(L.Tr("Apply (Regenerate Layer)"), GUILayout.Width(180)))
            {
                var error = AsyncSyncBuilder.Validate(request);
                if (error != null)
                {
                    EditorUtility.DisplayDialog(L.Tr("Async Sync"), error, "OK");
                }
                else
                {
                    AsyncSyncBuilder.Apply(request);
                    // Reload from what was actually saved (stale rates/requests filtered).
                    var applied = ConfigOf(controller, machine);
                    if (applied != null) _form.LoadConfig(applied);
                    Context.NotifyParametersChanged();
                    Context.NotifyGraphStructureChanged();
                }
                GUIUtility.ExitGUI();
            }
            EditorGUILayout.EndHorizontal();

            DrawRequestingStates(config);
        }

        /// <summary>The other half of the request feature, seen from the sync layer: every
        /// state that raises a request against this setup, with a jump to it.</summary>
        void DrawRequestingStates(GraphFrameData.AsyncSyncConfig config)
        {
            var requests = new List<GraphFrameData.SyncRequest>();
            foreach (var entry in GraphFrameData.GetSyncRequests(Context.Controller))
                if (entry.baseName == config.baseName)
                    requests.Add(entry);

            EditorGUILayout.Space(6);
            EditorGUILayout.LabelField(
                L.Tr("Requesting States") + " (" + requests.Count + ")", EditorStyles.boldLabel);
            if (requests.Count == 0)
            {
                EditorGUILayout.LabelField(
                    L.Tr("No state requests from this setup yet. Select a state and add a Sync Request in its inspector."),
                    EditorStyles.miniLabel);
                return;
            }

            foreach (var entry in requests)
            {
                EditorGUILayout.BeginHorizontal();
                EditorGUILayout.LabelField(entry.state.name + "  →  "
                    + string.Join(", ", entry.targets));
                if (GUILayout.Button(L.Tr("Select"), EditorStyles.miniButton, GUILayout.Width(56)))
                {
                    var location = ControllerLocator.Locate(Context.Controller, entry.state);
                    if (location != null)
                        Context.NavigateTo(location.layerIndex, location.stateMachinePath,
                            location.target);
                    GUIUtility.ExitGUI();
                }
                EditorGUILayout.EndHorizontal();
            }
        }
    }
}
